
package Clases;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseEvent;

public class Torres extends javax.swing.JFrame {

    
        private int x;
        private int y;

        protected void this_mousePressed(MouseEvent e) {
                x = e.getX();
                y = e.getY();
        }

        protected void this_mouseDragged(MouseEvent e) {
                Point point = MouseInfo.getPointerInfo().getLocation();
                setLocation(point.x - x, point.y - y);
        }
    public Torres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_disco3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_disco3.setBackground(new java.awt.Color(255, 204, 51));
        JP_disco3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JP_disco3MouseDragged(evt);
            }
        });
        JP_disco3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JP_disco3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout JP_disco3Layout = new javax.swing.GroupLayout(JP_disco3);
        JP_disco3.setLayout(JP_disco3Layout);
        JP_disco3Layout.setHorizontalGroup(
            JP_disco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        JP_disco3Layout.setVerticalGroup(
            JP_disco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(JP_disco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Sin título-3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Sin título-3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Sin título-3.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JP_disco3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_disco3MousePressed
        this_mousePressed(evt);
        
    }//GEN-LAST:event_JP_disco3MousePressed

    private void JP_disco3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_disco3MouseDragged
         this_mouseDragged(evt);
    }//GEN-LAST:event_JP_disco3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Torres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Torres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_disco3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
